### ISSUE TITLE
Make capability to set file extension for log file in LogConsoleSettings

### ISSUE THREAD

**Issue by Dshifu** [pixeption/MobileConsoleKit#2]
Hello!

I really love your plugin and recommend to everyone.

Can you create settings to be able to set custom file extension for shared log file.
Right now log file extension is .txt. And this files always open with notepad.
We want log file be with extension .log, so we can choose different program for this kind of files.

Right now this code not in lib so we can change it by hardcode, but it would be sooooo nice if we have this kind of capability in future version.

Thank you!

**Comment by pixeption** [comment]
Hi @Dshifu,
Thanks for using MCK.

I have planned to upload MCK with sources instead of DLL for a while and actually did it, but Unity Asset Store team reject it because of new screen shots rule compliance.

If you want one, please email to pixeption@gmail.com and I'm happy to send you full sources.
Also I can make changes to support error log type (https://github.com/pixeption/MobileConsoleKit/issues/3) before sending it to you.

**Comment by Dshifu** [comment]
It will be awesome!
Thank you so much!
Will contact you in moment.

So will you support changing file extension for sharing log file ?
